version: "3.8"

services:
  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=cinema
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - media_data:/vol/web/media
      - static_data:/vol/web/static
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=cinema
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - SECRET_KEY=django-insecure-6vubhk2$++agnctay_4pxy_8cq)mosmn(*-#2b^v4cgsh-^!i3
      - DEBUG=True
    depends_on:
      - db
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

volumes:
  db_data:
  media_data:
  static_data:
